?start: value

?value: object
      | array
      | string
      | SIGNED_NUMBER      -> number
      | "true"             -> true
      | "false"            -> false
      | "null"             -> null

array  : "[" [value ("," value)*] "]"
object : "{" [pair ("," pair)~5] "}"
pair   : string ":" value

inner: /([^"]|\\\")+/ |
string : "\"" inner "\""

%import common.SIGNED_NUMBER
%import common.WS

%ignore WS