# Grammar for subset of JSON
# String doesn't support unicode and escape yet
# If you don't need to generate unicode and escape, you can use this grammar
# We are working to support unicode and escape

root   ::= object

object ::= "{" ws string ":" ws value "," ws string ":" ws value "," ws string ":" ws value "," ws string ":" ws value "," ws string ":" ws value "," ws string ":" ws value "," ws string ":" ws value "," ws string ":" ws value "," ws string ":" ws value "," ws string ":" ws value "}"

value  ::= string

string ::= "\"" [ \t!#-\[\]-~]* "\"" ws

ws ::= ([ \t\n] ws)?